version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    restart: unless-stopped
  web:
    build: ./web
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    env_file:
      - web/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api

