export type Term = {
  before: string;
  after: string[];
  comment: string;
};

export type TermsDB = Record<string, Term[]>;

// מאגר מונחים מקיף (100+ ערכים) לפי קטגוריות
export const TERMS_DATABASE: TermsDB = {
  connecting_words: [
    { before: 'יש לציין כי', after: ['חשוב לדעת ש'], comment: 'מילת קישור מתורגמת' },
    { before: 'בנוסף לכך', after: ['בנוסף', 'כמו כן'], comment: 'חלופות טבעיות' },
    { before: 'יובהר כי', after: ['כדאי לדעת ש', 'חשוב להדגיש ש'], comment: 'ביטוי פורמלי מדי' },
    { before: 'עם זאת', after: ['אבל', 'למרות זאת'], comment: 'גיוון טבעי' },
    { before: 'למעשה', after: ['בפועל'], comment: 'שימוש יתר' },
    { before: 'ברם', after: ['אבל'], comment: 'ארכאי' },
    { before: 'על כן', after: ['לכן'], comment: 'פישוט לשון' },
    { before: 'לעיל', after: ['למעלה', 'כאמור'], comment: 'ארכאי' },
    { before: 'להלן', after: ['כאן', 'בהמשך'], comment: 'פישוט לשון' },
    { before: 'לאור זאת', after: ['לכן'], comment: 'פישוט לשון' },
    { before: 'למצער', after: ['לפחות'], comment: 'ארכאי' },
    { before: 'לחלופין', after: ['או'], comment: 'פישוט לשון' },
    { before: 'כפועל יוצא', after: ['כתוצאה מכך'], comment: 'ביטוי כבד' },
    { before: 'דהיינו', after: ['כלומר'], comment: 'ארכאי' },
    { before: 'כאמור לעיל', after: ['כאמור'], comment: 'קיצור' },
    { before: 'אשר על כן', after: ['לכן'], comment: 'ארכאי' },
    { before: 'מן הראוי לציין כי', after: ['כדאי לציין ש'], comment: 'כבדות לשון' },
    { before: 'בשים לב לכך', after: ['כיוון ש', 'מאחר ש'], comment: 'כבדות לשון' },
    { before: 'בנסיבות אלו', after: ['במצב הזה'], comment: 'פישוט לשון' },
    { before: 'בטרם', after: ['לפני'], comment: 'ארכאי' },
    { before: 'למותר לציין כי', after: ['ברור ש', 'מובן ש'], comment: 'יתירות' },
    { before: 'משכך', after: ['לכן'], comment: 'משפטי-ארכאי' },
    { before: 'הלכה למעשה', after: ['בפועל'], comment: 'כבדות לשון' },
    { before: 'כל אימת ש', after: ['בכל פעם ש'], comment: 'ארכאי' },
    { before: 'במידה ו', after: ['אם'], comment: 'תחביר לא תקני' },
  ],
  legal_terms: [
    { before: 'יורשי חובה', after: ['יורשים חוקיים'], comment: 'תקן ניסוח' },
    { before: 'המוריש', after: ['המנוח'], comment: 'מונח מודרני' },
    { before: 'עזבון', after: ['עיזבון'], comment: 'כתיב נכון' },
    { before: 'בזכאותו', after: ['זכאי ל', 'זכותו ל'], comment: 'תִרגום מאנגלית' },
    { before: 'טוען כי', after: ['טוען ש'], comment: 'פישוט תחביר' },
    { before: 'כמבואר', after: ['כמו שמוסבר'], comment: 'ארכאי' },
    { before: 'משיב', after: ['עונה', 'הנתבע'], comment: 'הנגשה' },
    { before: 'מבקש', after: ['התובע'], comment: 'הנגשה' },
    { before: 'כתב טענות', after: ['טענות בכתב'], comment: 'פישוט לשון' },
    { before: 'הוגש בזאת', after: ['מוגש'], comment: 'קיצור' },
    { before: 'לאלתר', after: ['מיד'], comment: 'ארכאי' },
    { before: 'בדחיפות', after: ['מיידית'], comment: 'דיוק' },
    { before: 'במותב תלתא', after: ['בהרכב שלושה שופטים'], comment: 'הבהרה' },
    { before: 'כבוד בית המשפט', after: ['בית המשפט'], comment: 'קיצור' },
    { before: 'לשיטתו', after: ['לדעתו'], comment: 'פישוט לשון' },
    { before: 'עתירה', after: ['בקשה לבית המשפט'], comment: 'הבהרה' },
    { before: 'החלטה זו', after: ['ההחלטה הזו'], comment: 'שפה טבעית' },
    { before: 'צו מניעה', after: ['צו שאוסר'], comment: 'הנגשה' },
    { before: 'צו עשה', after: ['צו שמחייב'], comment: 'הנגשה' },
    { before: 'למצער', after: ['לפחות'], comment: 'ארכאי' },
    { before: 'הלינו', after: ['התלוננו'], comment: 'ארכאי' },
    { before: 'מחד גיסא', after: ['מצד אחד'], comment: 'ארכאי' },
    { before: 'מאידך גיסא', after: ['מצד שני'], comment: 'ארכאי' },
    { before: 'ככל הנראה', after: ['כנראה'], comment: 'טבעיות' },
    { before: 'הגם ש', after: ['למרות ש'], comment: 'ארכאי' },
    { before: 'לשון הרע', after: ['הוצאת דיבה'], comment: 'הנגשה' },
    { before: 'אכיפה', after: ['אכיפת חוזה'], comment: 'דיוק' },
    { before: 'פיצוי מוסכם', after: ['קנס בחוזה'], comment: 'הנגשה' },
    { before: 'הפרת חוזה', after: ['שבירת הסכם'], comment: 'שפה טבעית' },
    { before: 'קניין רוחני', after: ['זכויות יוצרים וסימנים'], comment: 'הנגשה' },
    { before: 'חוק החוזים', after: ['חוק החוזים (התרופות/חלק כללי)'], comment: 'דיוק' },
  ],
  business_terms: [
    { before: 'בהתבסס על', after: ['בהסתמך על', 'על פי'], comment: 'תרגום ישיר' },
    { before: 'במסגרת של', after: ['במסגרת'], comment: 'יתירות' },
    { before: 'בעלי עניין', after: ['בעלי ענין'], comment: 'כתיב' },
    { before: 'אסטרטגיה', after: ['תוכנית פעולה'], comment: 'הנגשה' },
    { before: 'סינרגיה', after: ['שילוב כוחות'], comment: 'הנגשה' },
    { before: 'פיבוט', after: ['שינוי כיוון'], comment: 'הנגשה' },
    { before: 'סקייל', after: ['הגדלה', 'צמיחה'], comment: 'הנגשה' },
    { before: 'אופטימיזציה', after: ['שיפור'], comment: 'הנגשה' },
    { before: 'פרודקט', after: ['מוצר'], comment: 'עברית' },
    { before: 'פיצ׳רים', after: ['יכולות', 'תכונות'], comment: 'עברית' },
    { before: 'קי-פי-איי', after: ['מדדי הצלחה'], comment: 'עברית' },
    { before: 'Onboarding', after: ['חניכה'], comment: 'עברית' },
    { before: 'Roadmap', after: ['מפת דרכים'], comment: 'עברית' },
    { before: 'Kickoff', after: ['פתיחת פרויקט'], comment: 'עברית' },
    { before: 'Workflow', after: ['תהליך עבודה'], comment: 'עברית' },
    { before: 'Low hanging fruit', after: ['הישגים קלים'], comment: 'עברית' },
    { before: 'Best practices', after: ['שיטות מומלצות'], comment: 'עברית' },
    { before: 'Benchmark', after: ['השוואת ביצועים'], comment: 'עברית' },
    { before: 'Stakeholders', after: ['שותפים רלוונטיים'], comment: 'עברית' },
    { before: 'Budgeting', after: ['תכנון תקציב'], comment: 'עברית' },
    { before: 'Cash flow', after: ['תזרים מזומנים'], comment: 'עברית' },
    { before: 'Break-even', after: ['נקודת איזון'], comment: 'עברית' },
    { before: 'Market fit', after: ['התאמה לשוק'], comment: 'עברית' },
  ],
  style_terms: [
    { before: 'נידון', after: ['נדון'], comment: 'כתיב' },
    { before: 'חיפושים', after: ['חיפוש'], comment: 'ריבוי מיותר' },
    { before: 'בכדי', after: ['כדי'], comment: 'תקן תחבירי' },
    { before: 'מאד', after: ['מאוד'], comment: 'כתיב מלא' },
    { before: 'ועוד', after: ['וְעוֹד'], comment: 'טיפוגרפיה (אופציונלי)' },
    { before: 'דוגמא', after: ['דוגמה'], comment: 'כתיב' },
    { before: 'כגון', after: ['למשל'], comment: 'טבעיות' },
    { before: 'עקב כך', after: ['לכן'], comment: 'קיצור' },
    { before: 'בחינת', after: ['בדיקת'], comment: 'לשון משפטית' },
    { before: 'לעניות דעתי', after: ['לדעתי'], comment: 'כבדות לשון' },
    { before: 'כפועל יוצא מכך', after: ['כתוצאה מכך'], comment: 'כבדות לשון' },
    { before: 'מפאת', after: ['בגלל'], comment: 'ארכאי' },
    { before: 'כעת', after: ['עכשיו'], comment: 'שפה טבעית' },
    { before: 'למול', after: ['מול'], comment: 'תקן תחבירי' },
    { before: 'לשוויתי', after: ['לשוואתי'], comment: 'כתיב' },
    { before: 'שיטתי', after: ['שיטתי'], comment: '—' },
    { before: 'לאור האמור', after: ['לכן'], comment: 'קיצור' },
    { before: 'בהמשך לאמור', after: ['בהמשך'], comment: 'קיצור' },
    { before: 'לסבר את האוזן', after: ['כדי להמחיש'], comment: 'ביטוי ספרותי' },
    { before: 'לעניין זה', after: ['בנושא הזה'], comment: 'טבעיות' },
    { before: 'בכפוף ל', after: ['תחת'], comment: 'פישוט לשון' },
    { before: 'במסגרת זאת', after: ['במסגרת זו'], comment: 'כתיב' },
    { before: 'אותו ה', after: ['אותו'], comment: 'יתירות' },
    { before: 'האומר', after: ['שאומר'], comment: 'טבעיות' },
    { before: 'דנן', after: ['הזה'], comment: 'ארכאי' },
  ],
  punctuation_and_symbols: [
    { before: '"', after: ['״'], comment: 'מירכאות עבריות' },
    { before: "'", after: ['׳'], comment: 'גרש עברי' },
    { before: ' - ', after: [' — '], comment: 'מקף ארוך להדגשה' },
    { before: '...', after: ['…'], comment: 'שלוש נקודות טיפוגרפיות' },
    { before: ' ,', after: [', '], comment: 'ריווח תקני' },
    { before: ' .', after: ['. '], comment: 'ריווח תקני' },
    { before: ' ;', after: ['; '], comment: 'ריווח תקני' },
    { before: '( ', after: ['('], comment: 'ללא רווח לפני סוגר' },
    { before: ' )', after: [')'], comment: 'ללא רווח אחרי סוגר' },
    { before: ' %', after: ['%'], comment: 'ללא רווח לפני %' },
    { before: 'ק"מ', after: ['ק״מ'], comment: 'מירכאות כפולות' },
    { before: 'ק"ג', after: ['ק״ג'], comment: 'מירכאות כפולות' },
    { before: 'ס"מ', after: ['ס״מ'], comment: 'מירכאות כפולות' },
  ],
  english_to_hebrew: [
    { before: 'Email', after: ['דוא״ל'], comment: 'עברית' },
    { before: 'email', after: ['דוא״ל'], comment: 'עברית' },
    { before: 'AI', after: ['בינה מלאכותית'], comment: 'עברית' },
    { before: 'OK', after: ['בסדר'], comment: 'עברית' },
    { before: 'OK.', after: ['בסדר.'], comment: 'עברית' },
    { before: 'etc.', after: ['וכו׳'], comment: 'עברית' },
    { before: 'i.e.', after: ['כלומר'], comment: 'עברית' },
    { before: 'e.g.', after: ['לדוגמה'], comment: 'עברית' },
    { before: 'per se', after: ['כשלעצמו'], comment: 'עברית' },
    { before: 'de facto', after: ['למעשה'], comment: 'עברית' },
    { before: 'de jure', after: ['לפי חוק'], comment: 'עברית' },
    { before: 'FYI', after: ['לעיונך'], comment: 'עברית' },
    { before: 'ASAP', after: ['בהקדם'], comment: 'עברית' },
    { before: 'ETA', after: ['זמן הגעה משוער'], comment: 'עברית' },
    { before: 'to whom it may concern', after: ['למי שזה נוגע'], comment: 'עברית' },
  ],
};


